language: node_js
env: TRAVIS_CI=true
node_js:
- '0.12'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
deploy:
  provider: divshot
  environment:
    master: development
    staging: staging
    production: production
  skip_cleanup: true
  api_key:
    secure: CXMUKuxUta85Hfbh5FJDFfzu0K3L23vKVNmfDkWRUHVfMyJkesWEdK+u8NWvxARl6qjNypOpU2etPi1l0XAuqo3ePRZR1Z+Ws84bxMDT3750xDCzXx7YBjN1KqGjLlIgu3lp9cH6oNhEHBjptIEX9JJFmroYi1O9yRKy2zhYgE0jLVs/CRaRmIEukbf5SNO1t4UyTIBz3R7jc8PVL7bWLEfqkm/O83n3xp8OUr4gq9xiy1QEqG54gXvlVld0rZ5ty4WcnmhveTyXRzQB44VJmPL9Hhd4W0VHw1UMTVYDN4sBvBuLjDOJe470V08+f/xDTvmgmMBbRB4GzVgU0gWpLCzdu/SC4WGr1D6c150LTt490PNm1JiVWAZGamMK5ndhQVoPdlwvc4irhF9k/mA435JzXxvnwyCLFGvRLSPzG70QNupc1loqI5Wwjrnk0Muij1uSZzildJyUGLAcxSTH949XI1gQtBOZQ8pIysIaoJ68Yo9PkTfdE5qFXRfskG7BZAUOmxriaYoPmX4xlZ0cFdps25YUT2xysdpMdDIAsEJYHURc1lcxrmjytWxnlkoEgWj3j7AR1FipBerBMCqqiYQYPu9C3UOtIg9bAtfdbNgh+fpysOG1lwLRA7PDaoSPp3LEtkY1n2HEplzjldie+2wHllcE5CjSrNzMWRsFzAQ=
